#!/bin/bash
############################################################################
# Copyright 2020-2025 Ramon Fischer                                        #
#                                                                          #
# Licensed under the Apache License, Version 2.0 (the "License");          #
# you may not use this file except in compliance with the License.         #
# You may obtain a copy of the License at                                  #
#                                                                          #
#     http://www.apache.org/licenses/LICENSE-2.0                           #
#                                                                          #
# Unless required by applicable law or agreed to in writing, software      #
# distributed under the License is distributed on an "AS IS" BASIS,        #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. #
# See the License for the specific language governing permissions and      #
# limitations under the License.                                           #
############################################################################

###########################################################################
# $$\      $$\  $$$$$$\  $$$$$$$\  $$\   $$\ $$$$$$\ $$\   $$\  $$$$$$\   #
# $$ | $\  $$ |$$  __$$\ $$  __$$\ $$$\  $$ |\_$$  _|$$$\  $$ |$$  __$$\  #
# $$ |$$$\ $$ |$$ /  $$ |$$ |  $$ |$$$$\ $$ |  $$ |  $$$$\ $$ |$$ /  \__| #
# $$ $$ $$\$$ |$$$$$$$$ |$$$$$$$  |$$ $$\$$ |  $$ |  $$ $$\$$ |$$ |$$$$\  #
# $$$$  _$$$$ |$$  __$$ |$$  __$$< $$ \$$$$ |  $$ |  $$ \$$$$ |$$ |\_$$ | #
# $$$  / \$$$ |$$ |  $$ |$$ |  $$ |$$ |\$$$ |  $$ |  $$ |\$$$ |$$ |  $$ | #
# $$  /   \$$ |$$ |  $$ |$$ |  $$ |$$ | \$$ |$$$$$$\ $$ | \$$ |\$$$$$$  | #
# \__/     \__|\__|  \__|\__|  \__|\__|  \__|\______|\__|  \__| \______/  #
###########################################################################
#                                                                         #
# This shell script should be handled with care, since other repositories #
# are also using this script.                                             #
#                                                                         #
#                                                                         #
# The following permissions should be set:                                #
#                                                                         #
# /home/gitea/.local/share/gitea/hooks/post-receive.d/post-receive:       #
## owner: gitea                                                           #
## group: gitea                                                           #
## file access: 700                                                       #
#                                                                         #
# /home/gitea/.local/etc/gitea/tokens:                                    #
## owner: gitea                                                           #
## group: gitea                                                           #
## directory access: 700                                                  #
#                                                                         #
# /home/gitea/.local/etc/gitea/tokens/*.token:                            #
## owner: gitea                                                           #
## group: gitea                                                           #
## file access: 400                                                       #
#                                                                         #
###########################################################################

# function: git push mirror to:
## codeberg.org
## gitea.com
## github.com
## gitlab.com

daemon_username="gitea"
script_name="${0##*/}"
lock_file="/var/tmp/${script_name}.lock"
if [[ $(/usr/bin/id --user --name) != "${daemon_username}" ]]
then
    /bin/echo -e "\e[01;31mExecute this script as user '${daemon_username}'.\e[0m"
    exit 1
elif [[ -e "${lock_file}" ]]
then
    /bin/echo -e "\e[01;31mLock file '${lock_file}' is present, try pushing again in a few minutes...\e[0m"
    exit 1
else
    /bin/touch "${lock_file}"
fi

command_list=(git pwd rm sleep)
checkCommands()
{
    for current_command in "${command_list[@]}"
    do
        unalias ${current_command} 2>/dev/null
        if [[ ! $(command -v ${current_command} 2>/dev/null) ]]
        then
            /bin/echo -e "\e[01;31mcould not find command '${current_command}'.\e[0m"
            exit 1
        fi
    done
}

checkCommands

# refactor me: maybe use arrays here to provide more dynamic and readable variables
#              check, if files exist, before reading them
# credentials
## global
home_directory="/home/${daemon_username}"
token_directory="${home_directory}/.local/etc/${daemon_username}/tokens"
token_filename_suffix="token"
### "basename" has to be used here
current_repository_name=$(/usr/bin/basename $(/bin/pwd))
profile_username="keks24"
protocol_type="https"
## codeberg.org
codeberg_url="codeberg.org"
codeberg_username="${profile_username}"
codeberg_token_filename="${codeberg_url}.${token_filename_suffix}"
codeberg_token="$(< ${token_directory}/${codeberg_token_filename})"
codeberg_profile_url="${codeberg_url}/${codeberg_username}"
## gitea.com
#gitea_url="gitea.com"
#gitea_username="${profile_username}"
#gitea_token_filename="${gitea_url}.${token_filename_suffix}"
#gitea_token="$(< ${token_directory}/${gitea_token_filename})"
#gitea_profile_url="${gitea_url}/${gitea_username}"
## github.com
github_url="github.com"
github_username="${profile_username}"
github_token_filename="${github_url}.${token_filename_suffix}"
github_token="$(< ${token_directory}/${github_token_filename})"
github_profile_url="${github_url}/${github_username}"
## gitlab.com (important: the branch "master" is always protected by default)
gitlab_url="gitlab.com"
gitlab_username="${profile_username}"
gitlab_token_filename="${gitlab_url}.${token_filename_suffix}"
gitlab_token="$(< ${token_directory}/${gitlab_token_filename})"
gitlab_profile_url="${gitlab_url}/${gitlab_username}"

checkSanity()
{
    if [[ ${current_repository_name} == *"post-receive"* ]]
    then
        /bin/echo -e "\e[01;31mThis script should not be executed manually.\e[0m"
        removeLockFile
        exit 1
    fi
}

mirrorRepository()
{
    local username="${1}"
    local token="${2}"
    local url="${3}"

    # mirror push
    # should run in the background, due to long execution time
    /usr/bin/git push --mirror --quiet "${protocol_type}://${username}:${token}@${url}/${current_repository_name}" >/dev/null 2>&1 &
    /bin/echo "${protocol_type}://${url}/${current_repository_name}: mirror push initiated..."
    /bin/sleep 0.4
}

removeLockFile()
{
    /bin/rm --force "${lock_file}"
}

main()
{
    checkSanity

    ## codeberg.org
    mirrorRepository "${codeberg_username}" "${codeberg_token}" "${codeberg_profile_url}"
    ## gitea.com
    #mirrorRepository "${gitea_username}" "${gitea_token}" "${gitea_profile_url}"
    ## github.com
    mirrorRepository "${github_username}" "${github_token}" "${github_profile_url}"
    ## gitlab.com
    mirrorRepository "${gitlab_username}" "${gitlab_token}" "${gitlab_profile_url}"

    removeLockFile
}

main
